### PR TITLE
Add Unity files (unity-2019.4.36f1-mbe), commit hash 66f6777a1aa48e3f…

### PR DESCRIPTION
**Pull request by dartasen**
…7455172146303ced039fc2d7

### CODE REVIEW

**Comment by rzarai** [comment]
Hello. Will those help to debug rimworld version of unity? 

I ask this because of this issue: https://github.com/dnSpyEx/dnSpy/issues/167

**Comment by dartasen** [comment]
@Xeizzeth Subnautica is under this version (2019.4.36f1), but I can look to add 2019.4.30f1 too :)

**Comment by rzarai** [comment]
Yeah please do that. I would be much obliged.

**Comment by ElektroKill** [comment]
Please follow instructions in the README.md file carefully and create a accompanying pull request with the patched version of this source code to the `dnSpy` branch

**Pull request closed without merging**
